### ISSUE TITLE
Unable to remove KnativeKafka CR 

### ISSUE THREAD

**Issue by nrrso** [openshift-knative/serverless-operator#1308]
**Describe the bug**
Unable to delete the `KnativeKafka` custom resource (CR) while cleaning up the namespace 'knative-eventing'.

**Version**
Red Hat OpenShift Container Platform
Openshift Serverless version: 1.18.0
OpenShift version: 4.9.6
Kubernetes version: v1.22.1+d8c4430
Channel: candidate-4.9

**How to reproduce**
1. Remove `KnativeEventing` CR via OCP UI in namespace `knative-eventing`
2. Try Remove `KnativeKafka` CR via OCP UI (unresponsive, no effect)
3. Manual remove via oc cli: `oc delete KnativeKafka <NAME_OF_KNATIVE_KAFKA_CR> -n knative-eventing` (no effect)
4. Final cleanup of anything else: `oc delete deploy,svc,cm,secret --all -n knative-eventing`
5. Try namespace delete `oc delete ns knative-eventing` (perpetual `terminating` state)

**Potential root cause (suspicion):**
The finalizer implemented, relies on KnativeEventing CR and does not fully comply to https://kubernetes.io/docs/concepts/architecture/garbage-collection/. It is not apparent when deleting KnativeEventing CR, that KnativeKafka CR is reliant on it. 

I did try to remove the finalizer from the cr and got the following message:
```
oc replace -f /tmp/oc-edit-2388570947.yaml
Error from server (KnativeEventing instance must be installed before KnativeKafka): error when replacing "/tmp/oc-edit-2388570947.yaml": admission webhook "validating.knativekafkas.operator.serverless.openshift.io" denied the request: KnativeEventing instance must be installed before KnativeKafka
```

Edit - added output of namespace.status:
```
apiVersion: v1
kind: Namespace
[...]
status:
- lastTransitionTime: "2021-11-16T14:07:43Z"
    message: 'Some resources are remaining: knativekafkas.operator.serverless.openshift.io
      has 1 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2021-11-16T14:07:43Z"
    message: 'Some content in the namespace has finalizers remaining: knative-kafka-openshift
      in 1 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
 ```
