### ISSUE TITLE
Hide obsolete CRD in OLM

### ISSUE THREAD

**Issue by aliok** [openshift-knative/serverless-operator#149]
As per [OLM docs](https://docs.openshift.com/container-platform/4.3/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs)

apply the following annotation on the CSV to hide the obsolete CRD.
```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: my-operator-v1.2.3
  annotations:
    operators.operatorframework.io/internal-objects: '["my.internal.crd1.io","my.internal.crd2.io"]' 
...
```
