### ISSUE TITLE
disableRoute=true seems not to work

### ISSUE THREAD

**Issue by brunoNetId** [openshift-knative/serverless-operator#2533]
When a Service is created with the annotation `disableRoute`, it seems the flag is ignored and the route is created anyway

Here's the annotation definition I'm using:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    ...
    serving.knative.openshift.io/disableRoute: 'true'
```
