### ISSUE TITLE
1.6.0 incompatible with RedHat Openshift Service Mesh 

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift-knative/serverless-operator#286]
Found this out through trying it and realising I [couldn't call knative services when they were in a namespace in the mesh MemberRoll](https://github.com/openshift-knative/serverless-operator/issues/285#issuecomment-620492667).

Is there a plan to make these compatible? Just looking to know whether it's on the roadmap or if it's not core use-case?

**Comment by markusthoemmes** [comment]
Yes we're looking into that as part of our current backlog already.

**Comment by ryandawsonuk** [comment]
Happy to close this if it's being tracked elsewhere.

**Comment by nakfour** [comment]
@ryandawsonuk @markusthoemmes does adding a network policy that enables traffic to the knative service fix this issue?

**Comment by markusthoemmes** [comment]
@nakfour something around that does in theory work, yes

**Comment by brianredbeard** [comment]
cc @knrc

**Comment by knrc** [comment]
@brianredbeard We have an annotation which can be added to services to enable access, we deliberately partition the namespaces using NetworkPolicy to enforce the requirement for external SM invocations to come via the ingressgateway since a very common anti-pattern was to directly expose them via routes.

**Comment by ryandawsonuk** [comment]
@knrc is that the `maistra.io/expose-route: "true"` label?

**Comment by knrc** [comment]
@ryandawsonuk Yes, that's correct.  We install the [following network policy](https://github.com/Maistra/istio-operator/blob/maistra-1.1/resources/helm/overlays/istio/templates/networkpolicy.yaml#L43-L60) which enables access from the ingress routers to those with that label.  Does this help your use case?

**Comment by ryandawsonuk** [comment]
I've tried running the greeter example in an istio-enabled namespace with the expose-route label by applying:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greeter
spec:
  template:
    metadata:
      labels:
        maistra.io/expose-route: "true"
    spec:
      containers:
        - image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
          livenessProbe:
            httpGet:
              path: /healthz
          readinessProbe:
            httpGet:
              path: /healthz
          resources:
            limits:
              cpu: "0.8"
              memory: 200M
            requests:
              cpu: 200m
              memory: 100M
```
The label is then present on the Pod. Unfortunately the kservice is still not reachable externally. Am also not able to curl from inside the cluster. Will experiment with this some more.
