### ISSUE TITLE
Add the creation / update for a ConsoleCLIDownload resource

### ISSUE THREAD

**Issue by rhuss** [openshift-knative/serverless-operator#37]
In order to make the download of `kn` accessible in the console, the operator needs to create or update (or delete & create would also work) a resource that looks like

```yaml
apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: kn
spec:
  description: The OpenShift Serverless client `kn` is a CLI tool that allows you to fully manage OpenShift Serverless Serving and Eventing resources without writing a single line of YAML.
  displayName: kn - OpenShift Serverless CLI
  links:
  - href: https://mirror.openshift.com/pub/openshift-v4/clients/serverless/0.9.0/kn-linux-amd64-0.9.0.tar.gz
    text: Download kn (Linux)
  - href: https://mirror.openshift.com/pub/openshift-v4/clients/serverless/0.9.0/kn-macos-amd64-0.9.0.tar.gz
    text: Download kn (macOS)
  - href: https://mirror.openshift.com/pub/openshift-v4/clients/serverless/0.9.0/kn-windows-amd64-0.9.0.zip
    text: Download kn (Windows)
```

The version (0.9.0) in the example is the version of the kn release included in the serverless release.

This will lead automatically lead to a download page that looks like 

![grafik](https://user-images.githubusercontent.com/99080/69741423-4f55ff00-113b-11ea-84d7-6f2fb84abaeb.png)

In addition, the base URL (`https://mirror.openshift.com/pub/openshift-v4/clients`) must be configurable via the main Serverless CRD (e.g. via `knBaseDownloadUrl:` as there is also the requirement to support 'air-gapped' downloads when the cluster has no access to the internet. (the interesting bit would be from where to serve the binaries, but that's the second part of the story).

Ideally, the version number (0.9.0) is parameterizable and filled in just before the CO is created by the operator.
