### ISSUE TITLE
how to get autoscaler and activator metrics?

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift-knative/serverless-operator#897]
We're looking for autoscaler and activator metrics like in [4.1 version of serverless](https://docs.openshift.com/container-platform/4.1/serverless/monitoring-serverless.html).

But with [4.7 version we can only find basic resource metrics for serverless](https://docs.openshift.com/container-platform/4.7/serverless/monitoring/serverless-monitoring.html). Looking for e.g. autoscaler_actual_pods and activator_request_latencies_bucket. But neither autoscaler nor activator scraped by that prom either.

How would you suggest getting these metrics? Have tried adding a prometheus and telling it to scrape them. But it gets connection refused 

![image](https://user-images.githubusercontent.com/22754674/114580307-a5670c00-9c76-11eb-8b56-9a6f954c50e6.png)

We are using service mesh but have added both namespaces to the member roll and also tried adding this
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inbound
  namespace: knative-serving
spec:
  podSelector: {}
  ingress:
    - {}
```
Still get connection refused though.

We would use user-workload-monitoring but [we've got other problems with that](https://github.com/openshift/cluster-monitoring-operator/issues/1111). Is that the recommended way?
